    <footer id="website-footer">
        Questions? Feedback? Contact us!
        <div class="email-individual">
            <a class="send-email" href="mailto:rwijesinghe@swin.edu.au">
                <img class="individual-portrait" src="images/Ravinda-Wijesinghe.png" alt="tutor portrait">
            </a>
            <span class="tooltiptext">Email Ravinda!</span>
        </div>

        <div class="email-individual">
            <a class="send-email" href="mailto:104142281@student.swin.edu.au">
                <img class="individual-portrait" src="images/portrait.webp" alt="lucy portrait">
            </a>
            <span class="tooltiptext">Email Lucy!</span>
        </div>

        <div class="email-individual">
            <a class="send-email" href="mailto:104810423@student.swin.edu.au">
                <img class="individual-portrait" src="images/portrait.webp" alt="Eloise portrait">
            </a>
            <span class="tooltiptext">Email Eloise!</span>
        </div>

        <div class="email-individual">
            <a class="send-email" href="104934718@student.swin.edu.au">
                <img class="individual-portrait" src="images/portrait.webp" alt="Oshadi portrait">
            </a>
            <span class="tooltiptext">Email Oshadi!</span>
        </div>
    </footer>