    <header id="website-header">
        <div id="header-left">
            <a href="index.php"><img id="header-js-icon" src="images/header-icon.png" alt="javascript icon"></a>
            <p class="header-title">Introduction to Javascript</p>
        </div>

        <nav id="header-right">
            <ul class="nav-list">
                <li class="nav-list-item"><a href="index.php" class="header-navigation-link">HOME</a></li>

                <li class="nav-list-item"><a href="topic.php" class="header-navigation-link">WHAT IS JAVASCRIPT?</a>
                </li>

                <li class="nav-list-item"><a href="quiz.php" class="header-navigation-link">TEST YOUR KNOWLEDGE</a>
                </li>

                <li class="nav-list-item"><a href="enhancements1.html" class="header-navigation-link">ENHANCEMENTS 1</a>
                </li>

                <li class="nav-list-item"><a href="enhancements2.html" class="header-navigation-link">ENHANCEMENTS 2</a>
                </li>

                <li class="nav-list-item"><a href="manage.php" id="supervisor-item" class="header-navigation-link">SUPERVISOR</a>
                </li>
            </ul>
        </nav>
    </header>